### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/datamart-solution#13]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reflection

- [ ] No TODO markers left in reflection.md
- [x] All questions answered in reflection.md

## Creator Commissions

- [x] No TODO markers left in data_creator.py
- [ ] registry.csv file exists in builder&#x2F;data&#x2F;registry.csv
- [ ] builder&#x2F;data_creator.py creates an additional empty list
- [ ] builder&#x2F;data_creator.py features a list that uses the .append method
- [ ] builder&#x2F;data_creator.py features a list that uses add_names function

## Builder Business

- [x] No TODO markers left in table_builder.py
- [ ] table columns are in the order requested by the README
- [ ] builder&#x2F;table_builder.py uses the DATA list to add to table
- [ ] builder&#x2F;table_builder.py appends to the COLS variable when adding columns
- [ ] builder&#x2F;table_builder.py uses the pop() method to remove from row and&#x2F;or column
- [ ] builder&#x2F;table_builder.py implements a function called add_column with 1 parameter
- [ ] builder&#x2F;table_builder.py calls add_column with 1 argument
- [ ] builder&#x2F;table_builder.py implements a function called get_row with 1 parameter
- [ ] builder&#x2F;table_builder.py calls add_column with 1 argument
- [ ] builder&#x2F;table_builder.py implements a function called add_to_row with 2 parameters
- [ ] builder&#x2F;table_builder.py calls add_to_row with 2 arguments
- [ ] builder&#x2F;table_builder.py implements a function called remove_from_row with 1 parameter
- [ ] builder&#x2F;table_builder.py calls add_column with 1 argument

## Arranger Assignments

- [x] No TODO markers left in table_arranger.py
- [ ] arranger&#x2F;table_arranger.py uses the index method to retrieve list addresses
- [ ] arranger&#x2F;table_arranger.py uses a for loop with the DATA variable to switch columns
- [ ] arranger&#x2F;table_arranger.py implements a switch_columns function with 2 parameters
- [ ] arranger&#x2F;table_arranger.py calls switch_columns with 2 arguments
- [ ] arranger&#x2F;table_arranger.py calls the sorter function with one argument

## Analyzer Activities

- [x] No TODO markers left in table_analyzer.py
- [ ] analyzer&#x2F;table_analyzer.py uses the len() function to compute averages
- [ ] analyzer&#x2F;table_analyzer.py uses for loops with the DATA variable to discover data
- [ ] analyzer&#x2F;table_analyzer.py implements a counter function with 1 parameter
- [ ] analyzer&#x2F;table_analyzer.py calls the counter function with one argument
- [ ] analyzer&#x2F;table_analyzer.py implements a avg_column function with 1 parameter
- [ ] analyzer&#x2F;table_analyzer.py calls the avg_column function with one argument
- [ ] analyzer&#x2F;table_analyzer.py implements a max_value function with 1 parameter
- [ ] analyzer&#x2F;table_analyzer.py calls the max_value function with one argument

## Percent complete

Based on the checks achieved, this assignment is `14%` complete.
